# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "3.4"
  - "2.7"
  - "pypy"
  - "pypy3"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U .
  - pip install flake8

# command to run tests, e.g. python setup.py test
script:
  - py.test
  - flake8
